### ISSUE TITLE
Wireflow nummereren

### ISSUE THREAD

**Issue by Amber-vdr** [saschavanvliet/fix-the-flow-wireflow#1]
Je wireflow ziet er heel goed uit. Het is erg duidelijk en overzichtelijk! Een paar puntjes om je wireflow te verbeteren: nummereren.

Daarnaast nog je opdracht documenteren in de wiki. Voor de rest helemaal top.

**Comment by saschavanvliet** [comment]
Dankjewel! Ik heb het nu genummerd en ga het in github zetten.

**Comment by saschavanvliett** [comment]
Dankjewel! Ik heb het nu genummerd en ga het in github zetten.
